### ISSUE TITLE
Elevator.py: Unable to process "older" WRF files from the RAV2 dataset

### ISSUE THREAD

**Issue by olafurrognvaldsson** [Belgingur/WrfUtils#24] opened 2020-01-23 23:36 UTC
When I try to run the latest version of Elevator.py on this file here `sleggjan:/home/or/data/wrfout_d02_2018-08-21_00_test.nc4` I get an error stating
`RuntimeError: NetCDF: Attempting netcdf-4 operation on strict nc3 netcdf-4 file`
even if the file is on a netCDF4 format.
For further information, see logfile
[elevator.log.txt](https://github.com/Belgingur/WrfUtils/files/4106105/elevator.log.txt)

**Comment by logi** [comment] 2020-01-24 08:28
@olafurrognvaldsson The elevator log file seems to be empty

**Comment by olafurrognvaldsson** [comment] 2020-01-24 08:33
@logi hmm, I see this
![Screen Shot 2020-01-24 at 08 32 51](https://user-images.githubusercontent.com/18738411/73055211-283e5400-3e84-11ea-8b89-3c24d8918565.png)
when I open it

**Comment by logi** [comment] 2020-01-24 08:42
Weird. But I've gotten the text by round-about means.

**Comment by logi** [comment] 2020-01-24 08:53
This stack-trace shows that it's an error in creating an output variable with data-type `uint32` in a `NETCDF4_CLASSIC` which doesn't support unsigned variables:
```
2020-01-22 13:42:04 |    INFO |     PB             (Time,bottom_top,south_north,west_east): uint32 * 0.01 + 0
Traceback (most recent call last):
  File "/home/or/Belgingur-Utils/WrfUtils/DropDigits/Elevator.py", line 334, in <module>
    main()
  File "/home/or/Belgingur-Utils/WrfUtils/DropDigits/Elevator.py", line 216, in main
    process_file(geo_ds, geo_margin, in_file, out_file, config=config)
  File "/home/or/Belgingur-Utils/WrfUtils/DropDigits/Elevator.py", line 260, in process_file
    create_output_variables(in_ds, geo_ds, CALCULATORS, out_ds, out_var_names, comp_level, chunking, len(heights), height_unit)
  File "/home/or/Belgingur-Utils/WrfUtils/DropDigits/Elevator.py", line 151, in create_output_variables
    chunksizes=chunk_sizes)
  File "netCDF4/_netCDF4.pyx", line 2557, in netCDF4._netCDF4.Dataset.createVariable
  File "netCDF4/_netCDF4.pyx", line 3537, in netCDF4._netCDF4.Variable.__init__
  File "netCDF4/_netCDF4.pyx", line 1754, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Attempting netcdf-4 operation on strict nc3 netcdf-4 file
all done
```

The reason for making classic NC4 files is that they can be opened with `MFDataset` so an entire series of them can be processed together.

Also, 32 bit integers are the same size as floats. If you can't store the value as a 16 bit integer, just store the original float value which doesn't lose any range or precision. But this PB variable seems to have been processed in 2018 (date format was wrong and I've just pushed a fix for that):
```
string :history = "Created with python at 2018-12-09 06:27:13 by or" ;
```

**Comment by logi** [comment] 2020-01-24 08:58
`Elevator` creates output variables with the same data-types etc as input variables: https://github.com/Belgingur/WrfUtils/blob/87a0d670abc2ba9143129420338d2ce9e8b76aa2/DropDigits/Elevator.py#L114

I can insert a function which maps any unsigned datatypes to the corresponding signed type and adjusts add_offset accordingly.

**Comment by logi** [comment] 2020-01-24 10:38
I can now Elevate the test file locally. @olafurrognvaldsson can you please try again and sanity check? If it fails, attach a new log using the new `--verbose` flag.

**Comment by olafurrognvaldsson** [comment] 2020-01-24 11:19
@logi it does not fail, but the values of `pressure` are all negative for some reason, see attached screenshot
![Screen Shot 2020-01-24 at 11 09 38](https://user-images.githubusercontent.com/18738411/73065216-f2589a00-3e9a-11ea-93b0-b020e151fe14.png)
Other variables (e.g. both `P` and `PB` and `temperature`) look normal though

**Comment by olafurrognvaldsson** [comment] 2020-01-24 11:20
here is the log file
[elevator.log.txt](https://github.com/Belgingur/WrfUtils/files/4108079/elevator.log.txt)

**Comment by logi** [comment] 2020-01-24 12:49
This looks perfectly fine here, writing only `PB` and `pressure` at the same heights as you: 
```
(DropDigits) logi@saxi:~/belgingur.is/WrfUtils.git/DropDigits$ ./Elevator.py wrfout_d02_2018-08-21_00_test.nc4
/home/logi/belgingur.is/WrfUtils.git/DropDigits/utils.py:167: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  logging_config = yaml.load(configFile)
2020-01-24 13:46:54 |    INFO | Configured logging from /home/logi/belgingur.is/WrfUtils.git/DropDigits/logging.yml
2020-01-24 13:46:54 |    INFO | Load config from Elevator.yml
./Elevator.py:73: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(configFile)
2020-01-24 13:46:54 |    INFO | Interpolate variables to 40m, 60m, 80m, 100m, 120m, 150m, 170m, 200m above ground
2020-01-24 13:46:54 |    INFO |
2020-01-24 13:46:54 |    INFO | Opening input dataset wrfout_d02_2018-08-21_00_test.nc4
2020-01-24 13:46:54 |    INFO | Creating output file ./wrfout_d02_2018-08-21_00_test_elevated.nc4
2020-01-24 13:46:54 | WARNING | Will overwrite existing file
2020-01-24 13:46:54 |    INFO | Setting/updating global file attributes for output file
2020-01-24 13:46:54 |    INFO | Copy 120 attributes
2020-01-24 13:46:54 |    INFO | Add attributes:
2020-01-24 13:46:54 |    INFO |     history = Created with python at 2018-27-09 06:12:13 by or
2020-01-24 13:46:54 |    INFO |     history1 = Converted with Elevator.py at 2020-01-24 13:46:54 by logi on saxi
2020-01-24 13:46:54 |    INFO |     source = /sleggjan/shared/output/RAV2/2017-18/wrfout_d02_2018-08-21_00:00:00
2020-01-24 13:46:54 |    INFO |     source1 = wrfout_d02_2018-08-21_00_test.nc4
2020-01-24 13:46:54 |    INFO |     institution = Belgingur
2020-01-24 13:46:54 |    INFO |     institution1 = Belgingur
2020-01-24 13:46:54 |    INFO |     interpolation = Interpolated to 40m, 60m, 80m, 100m, 120m, 150m, 170m, 200m above ground
2020-01-24 13:46:54 |    INFO |     description = Reduced version of: Reduced version of: /sleggjan/shared/output/RAV2/2017-18/wrfout_d02_2018-08-21_00:00:00
2020-01-24 13:46:54 |    INFO | Add output dimensions:
2020-01-24 13:46:54 |    INFO |     Time (unlimited)
2020-01-24 13:46:54 |    INFO |     bottom_top (8)
2020-01-24 13:46:54 |    INFO |     south_north (235)
2020-01-24 13:46:54 |    INFO |     west_east (305)
2020-01-24 13:46:54 |    INFO | Create output variables with:
2020-01-24 13:46:54 |    INFO |     Avoid NC4C incompatible type uint32 * 0.01 + 0
2020-01-24 13:46:54 |    INFO |     PB             (Time,bottom_top,south_north,west_east): int32 * 0.01 + 21474836.48
2020-01-24 13:46:54 |    INFO |     pressure       (Time,bottom_top,south_north,west_east): int16 * 2 + 65536
2020-01-24 13:46:54 |    INFO | Processing data in chunks of 32 time steps
2020-01-24 13:46:54 |    INFO | Chunk[0:2]: 2018-08-21 00:00:00 - 2018-08-21 01:00:07
2020-01-24 13:46:54 |    INFO | Processing Variable
2020-01-24 13:46:54 |    INFO |     PB
2020-01-24 13:46:54 |    INFO |         read PB
2020-01-24 13:46:54 |    INFO |         calculate z
2020-01-24 13:46:54 |    INFO |         calculate z_stag
2020-01-24 13:46:54 |    INFO |         make aligned interpolator for [40, 60, 80, 100, 120, 150, 170, 200]
2020-01-24 13:46:55 |    INFO |         interpolate on: bottom_top
2020-01-24 13:46:55 |    INFO |         0.760s
2020-01-24 13:46:55 |    INFO |     pressure
2020-01-24 13:46:55 |    INFO |         read P
2020-01-24 13:46:55 |    INFO |         interpolate on: bottom_top
2020-01-24 13:46:55 |    INFO |         cached PB
2020-01-24 13:46:55 |    INFO |         calculate pressure
2020-01-24 13:46:55 |    INFO |         0.198s
2020-01-24 13:46:55 |    INFO | Size: 101,828 MB -> 7,275 MB, reduced to 7.1% in 1.0 s
```

Reading the data back:
```
(DropDigits) logi@saxi:~/belgingur.is/WrfUtils.git/DropDigits$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4 as nc
>>> import numpy as np
>>>
>>> ds = nc.Dataset('wrfout_d02_2018-08-21_00_test_elevated.nc4')
>>> var=ds.variables['PB']
>>> print(var)
<class 'netCDF4._netCDF4.Variable'>
int32 PB(Time, bottom_top, south_north, west_east)
    description: BASE STATE PRESSURE
    least_significant_digit: 2
    scale_factor: 0.01
    offset: 21474836.48
unlimited dimensions: Time
current shape = (2, 8, 235, 305)
filling on, default _FillValue of -2147483647 used

>>>
>>> for h in range(var.shape[1]):
...    v = var[:,h]
...    print(h, np.min(v), np.max(v))

0 78210.27 99526.7
1 78013.34 99290.32
2 77816.89 99054.6
3 77620.92 98819.44
4 77425.31 98584.8
5 77132.54000000001 98233.75
6 76937.86 98000.29000000001
7 76646.57 97651.0
```

Viewing it:
![mynd](https://user-images.githubusercontent.com/217723/73070038-9f3d1200-3eaf-11ea-8f3e-96049e55ec2c.png)

**Comment by logi** [comment] 2020-01-24 12:51
Are you perhaps talking about #25 now?

**Comment by olafurrognvaldsson** [comment] 2020-01-24 13:02
@logi the base state pressure is fine (i.e. variable `PB`), it is the derived variable `pressure` that looks strange (all negative values)

**Comment by olafurrognvaldsson** [comment] 2020-01-24 13:03
The screenshot above is of `PB`, not `pressure`

**Comment by logi** [comment] 2020-01-24 13:11
Ah, yes, I have negative pressures locally as well.

I had written this these instructions for updating conda and recreate the conda environments and it is probably worth doing (occasionally) anyway.


Update conda and set it up in bash:
```
conda update -n base -c defaults conda
conda init bash
. ~/.bashrc
```

Change to the DropDigits folder and recreate the conda envrionment:
```
conda deactivate
conda env remove --name DropDigits
conda env create
conda activate DropDigits
```

**Comment by logi** [comment] 2020-01-24 13:18
Running `./Elevator.py -v wrfout_d02_2018-08-21_00_test.nc4` I get this bit logged to console:
```
2020-01-24 14:14:25 |    INFO |     pressure
2020-01-24 14:14:25 |    INFO |         read P
2020-01-24 14:14:25 |    INFO |         interpolate on: bottom_top
2020-01-24 14:14:25 |    INFO |         cached PB
2020-01-24 14:14:25 |    INFO |         calculate pressure
2020-01-24 14:14:25 |    INFO |         range: 76997.6 .. 101063
2020-01-24 14:14:25 |    INFO |         0.248s
```
but reading the values back:
```python
import netCDF4 as nc
import numpy as np

ds = nc.Dataset('wrfout_d02_2018-08-21_00_test_elevated.nc4')
var=ds.variables['pressure']
print(var)

for h in range(var.shape[1]):
   v = var[:,h]
   print(h, np.min(v), np.max(v))
```
I get these ranges:
```
0 -32768 32766
1 -32768 32766
2 -32768 32766
3 -32768 32766
4 -32768 32766
5 -32768 32766
6 -32768 32766
7 -32768 32766
```
so the issue is present here and without using `ncview`

**Comment by logi** [comment] 2020-01-24 13:25
@olafurrognvaldsson Do the values look correct to you if you add `131072` to them? That's `2*65536` or `scale_factor*offset`

**Comment by olafurrognvaldsson** [comment] 2020-01-24 13:28
Yes, that would result in ~1.008 hPa out at see, which is totally believable, assuming there was a high pressure ridge over the region

**Comment by logi** [comment] 2020-01-24 13:29
At 40m .. 200m AGL I'm seeing a range of -54074 .. -30008 in ncview which would map to 76998 .. 101064

**Comment by logi** [comment] 2020-01-24 13:30
OK, so for some reason the offset value is being ignored when the variable is read back in for `pressure` but not for e.g. `PB`. Fun.

**Comment by olafurrognvaldsson** [comment] 2020-01-24 13:34
This is strange indeed. The values for `pressure` are fine when used internally to calculate e.g. `temperature`

**Comment by logi** [comment] 2020-01-24 13:34
@olafurrognvaldsson wait, isn't this issue actually done and we're now talking about #25?

**Comment by olafurrognvaldsson** [comment] 2020-01-24 13:36
Arrghhh, yes you are right

**Closed** 2020-01-24 13:36 UTC
Labels: bug
